
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2026 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: User Supported IDCODES
*
*******************************************************************/

#ifndef XILSKEY_IDCODES_H
#define XILSKEY_IDCODES_H

#ifdef __cplusplus
extern "c" { 
#endif

#include "xilskey_utils.h"

/* No Value specified, assigning default values */
#define XSK_USER_DEVICE_SERIES	XSK_FPGA_SERIES_ZYNQ
#define XSK_USER_DEVICE_ID	0
#define XSK_USER_DEVICE_IRLEN	0
#define XSK_USER_DEVICE_NUMSLR	1
#define XSK_USER_DEVICE_MASTER_SLR 0

#ifdef __cplusplus
extern "c" { 
#endif

#endif /* XILSKEY_IDCODES_H */
